name: DÃ©ploiement Rec

on:
  push:
    branches:
      - main

jobs:
  deploy-rec:
    runs-on: self-hosted

    steps:
      - name: ğŸ”„ RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: ğŸš€ Properties nwleaderboard-rec
        run: |
          cd /opt/propertiesmanager-connector
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "nwleaderboard" "main" "rec" "${{ github.workspace }}/nwleaderboard-ui/config/config.js"
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "nwleaderboard" "main" "rec" "${{ github.workspace }}/nwleaderboard-api/src/main/resources/application.properties"
          cd ${{ github.workspace }}

      - name: ğŸš€ DÃ©ploiement sur nwleaderboard-rec
        run: |
          cd nwleaderboard-ui
          export CONFIG_ENV=rec
          echo "ğŸ“¦ Installation des dÃ©pendances..."
          npm install

          echo "ğŸ—ï¸  Build du site..."
          npm run build

          echo "ğŸ” VÃ©rification du dossier dist/"
          if [ ! -d "dist" ]; then
            echo "âŒ Le dossier 'dist/' n'a pas Ã©tÃ© gÃ©nÃ©rÃ©. Abandon."
            exit 1
          fi

          echo "ğŸ§¹ Nettoyage du dossier de test..."
          rm -rf /opt/nwleaderboard/nwleaderboard-rec/*

          echo "ğŸ“ Copie des fichiers dans nwleaderboard-rec..."
          cp -r dist/* /opt/nwleaderboard/nwleaderboard-rec/

          echo "âœ… DÃ©ploiement du front REC terminÃ© !"

          cd ../nwleaderboard-api
          echo "ğŸ“¦ Installation des dÃ©pendances..."
          mvn clean package

          echo "ğŸ” VÃ©rification du dossier target/"
          if [ ! -d "target" ]; then
            echo "âŒ Le dossier 'target/' n'a pas Ã©tÃ© gÃ©nÃ©rÃ©. Abandon."
            exit 1
          fi

          echo "ğŸ§¹ Nettoyage du dossier de test..."
          rm -rf /opt/nwleaderboard/nwleaderboard-api-rec/nwleaderboard-api-runner.jar

          echo "ğŸ“ Copie des fichiers dans nwleaderboard-api-rec..."
          cp -r target/nwleaderboard-api-1.0.0-SNAPSHOT-runner.jar /opt/nwleaderboard/nwleaderboard-api-rec/nwleaderboard-api-runner.jar
          sudo chown nwleaderboard-api-rec: /opt/nwleaderboard/nwleaderboard-api-rec/nwleaderboard-api-runner.jar
          cp ${{ github.workspace }}/nwleaderboard-api/src/main/resources/application.properties /opt/nwleaderboard/nwleaderboard-api-rec/config/application.properties

          echo "ğŸ“ redemarrage du service..."
          sudo systemctl restart quarkus-nwleaderboard-api-rec.service

          echo "âœ… DÃ©ploiement REC terminÃ© !"
