---
name: DÃ©ploiement Pro

'on':
  push:
    tags:
      - '*.*.*'
      - '*.*.*.*'

permissions:
  contents: write

jobs:
  deploy-pro:
    runs-on: self-hosted

    steps:
      - name: ğŸ”„ RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: ğŸš€ DÃ©ploiement sur nwleaderboard-pro
        run: |
          cd /opt/propertiesmanager-connector
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "nwleaderboard" "${{ github.ref_name }}" "pro" "${{ github.workspace }}/nwleaderboard-ui/config/config.js"
          java -jar propertiesmanager-java-connector-runner.jar UPDATE "nwleaderboard" "${{ github.ref_name }}" "pro" "${{ github.workspace }}/nwleaderboard-api/src/main/resources/application.properties"
          cd ${{ github.workspace }}

      - name: â˜• Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: ğŸ—ï¸ Build standard
        run: |
          cd nwleaderboard-ui
          export CONFIG_ENV=pro
          echo "ğŸ“¦ Installation des dÃ©pendances..."
          npm install

          echo "ğŸ—ï¸  Build du site..."
          npm run build

      - name: â˜• Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: ğŸš€ DÃ©ploiement du front sur nwleaderboard-pro
        run: |
          cd nwleaderboard-ui
          export CONFIG_ENV=pro
          npm run build

          echo "ğŸ” VÃ©rification du dossier dist/"
          if [ ! -d "dist" ]; then
            echo "âŒ Le dossier 'dist/' n'a pas Ã©tÃ© gÃ©nÃ©rÃ©. Abandon."
            exit 1
          fi

          echo "ğŸ§¹ Nettoyage du dossier de test..."
          rm -rf /opt/nwleaderboard/nwleaderboard-pro/*

          echo "ğŸ“ Copie des fichiers dans nwleaderboard-pro..."
          cp -r dist/* /opt/nwleaderboard/nwleaderboard-pro/

          echo "âœ… DÃ©ploiement du front PRO terminÃ© !"

      - name: ğŸš€ generation de l'aab
        run: |
          cd nwleaderboard-ui
          export CONFIG_ENV=pro
          npm run build:aab

          echo "ğŸ” VÃ©rification du dossier dist/"
          if [ ! -d "dist" ]; then
            echo "âŒ Le dossier 'dist/' n'a pas Ã©tÃ© gÃ©nÃ©rÃ©. Abandon."
            exit 1
          fi

          echo "âœ… generation de l'aab terminÃ© !"

      - name: â˜• Set up JDK 21 for API
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: ğŸš€ DÃ©ploiement de l'API PRO
        run: |
          cd nwleaderboard-api
          echo "ğŸ“¦ Installation des dÃ©pendances..."
          mvn clean package

          echo "ğŸ” VÃ©rification du dossier target/"
          if [ ! -d "target" ]; then
            echo "âŒ Le dossier 'target/' n'a pas Ã©tÃ© gÃ©nÃ©rÃ©. Abandon."
            exit 1
          fi

          echo "ğŸ§¹ Nettoyage du dossier de test..."
          rm -rf /opt/nwleaderboard/nwleaderboard-api-pro/nwleaderboard-api-runner.jar

          echo "ğŸ“ Copie des fichiers dans nwleaderboard-api-pro..."
          cp -r target/nwleaderboard-api-1.0.0-SNAPSHOT-runner.jar /opt/nwleaderboard/nwleaderboard-api-pro/nwleaderboard-api-runner.jar
          sudo chown nwleaderboard-api-pro: /opt/nwleaderboard/nwleaderboard-api-pro/nwleaderboard-api-runner.jar
          cp ${{ github.workspace }}/nwleaderboard-api/src/main/resources/application.properties /opt/nwleaderboard/nwleaderboard-api-pro/config/application.properties

          echo "ğŸ“ redemarrage du service..."
          sudo systemctl restart quarkus-nwleaderboard-api-pro.service

          echo "âœ… DÃ©ploiement PRO terminÃ© !"

      - name: ğŸ“¦ Attacher l'AAB Ã  la release
        uses: softprops/action-gh-release@v1
        with:
          files: nwleaderboard-ui/app-release-bundle.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
